spring:
  application:
    name: mall-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/mall_db
    username: monscao
    password:
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB

server:
  port: 8080

auth:
  jwt-secret: 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
  token-expiration-minutes: 120
